/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package gradleTest.Increment;

import java.lang.Math;

public class App03 {
    public static double getAngle(int x1, int y1, int x2, int y2)
    {
        int dx = x2 - x1;
        int dy = y2 - y1;
        //if(dy == 0) return 0;
        double d = dx/dy;
        double angle = Math.atan(d);
        return angle;
    }
}
